### ISSUE TITLE
Can we avoid manual secret management?

### ISSUE THREAD

**Issue by davidanthoff** [julia-actions/julia-uploadcodecov#1]
Right now package authors need to store an access token as a secret in their package repository. Somehow travis and appveyor get around that step. I don't understand how, but it would be much nicer if one didn't have to deal with these secrets at all.

**Comment by davidanthoff** [comment]
And another problem: I think [this PR](https://github.com/davidanthoff/StringBuilders.jl/pull/13) failed like [this](https://github.com/davidanthoff/StringBuilders.jl/commit/cf4965a1909839bc6e0c7588a52accad9dc1792e/checks) because the secret might not be made available for PR builds. That is a real bummer, of course...

**Comment by davidanthoff** [comment]
More info [here](https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/m-p/30678).

**Comment by SaschaMann** [comment]
It seems that Travis and Appveyor work without token because Codecov can infer the repository somehow: https://github.com/lemurheavy/coveralls-public/issues/208#issuecomment-34475013

I came across [codecov/codecov-action](https://github.com/codecov/codecov-action) while looking into this and even their own action requires the token, so I doubt there's a way around it (yet).

**Comment by SaschaMann** [comment]
I came across [codecov/codecov-action](https://github.com/codecov/codecov-action) while looking into this and even their own action requires the token, so I doubt there's a way around it (yet).

**Comment by Wikunia** [comment]
I just came across it. I have the same problem that PRs from other users don't contain the codecov report. Hope this gets fixed somehow.

**Comment by SaschaMann** [comment]
@Wikunia As mentioned in the [thread](https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/m-p/30678) David linked above, a workaround would be to just expose the token. It feels very wrong but the potential risk seems rather low. Perhaps worth considering until there's a proper solution.

**Comment by DilumAluthge** [comment]
From https://docs.codecov.io/docs/frequently-asked-questions:
> The upload token is required for all uploads, except originating from **public project** using Travis-CI, Circle CI, or AppVeyor CI.

How do Travis-CI, Circle CI, and AppVeyor CI get around this requirement?

**Comment by davidanthoff** [comment]
Unclear to me...

**Comment by DilumAluthge** [comment]
This thread seems very useful: https://community.codecov.io/t/whitelist-github-action-servers-to-upload-without-a-token/491

The latest post (28 days ago):
> We’ll make sure to update our community as soon as tokenless uploads for GitHub Actions are available. For the time being, there is still no public API for Actions, which means the repository token remains the only method of authentication for those repositories. We’ve been in contact with people at GitHub and their Actions API is scoped to be released early next year, so we plan on delivering this feature as soon as it comes out.
> 
> I certainly empathize with your organization’s circumstances and understand that it can be hard to manage contributors who don’t have access to secrets. In the meantime, I’m glad you’re utilizing tokenless uploads via Travis :slight_smile:

So it seems like CodeCov is planning on implementing tokenless uploads for GitHub Actions, but not until GitHub releases a public API for Actions, which apparently won't be until sometime this year.

**Comment by DilumAluthge** [comment]
https://community.codecov.io/t/whitelist-github-action-servers-to-upload-without-a-token/491/15?u=dilumaluthge

> Tokenless uploads for GitHub Actions is the works

So now that the GitHub Actions API is in public beta (https://github.blog/changelog/2020-01-27-github-actions-api-beta/), it looks like CodeCov is working on tokenless uploads.

**Comment by Nosferican** [comment]
https://community.codecov.io/t/whitelist-github-action-servers-to-upload-without-a-token/491/17?u=nosferican

They have now released it as of 2020-02-04.

**Comment by davidanthoff** [comment]
I'm actually no longer using this action here, instead I'm using the official codecov action in combination with a new `julia-processcoverage` action, see an example [here](https://github.com/davidanthoff/StringBuilders.jl/blob/master/.github/workflows/jlpkgbutler-ci-master-workflow.yml#L32). That is what the package butler does now. I think overall that is simpler. Because we no longer have to maintain the upload stuff at all.

**Comment by Nosferican** [comment]
Worked perfectly!
May I suggest closing this issue and archiving the repository after putting a deprecating notice on the README?

**Comment by Wikunia** [comment]
The package `julia-processcoverage`:
https://github.com/julia-actions/julia-processcoverage currently doesn't have a readme. 
I'm forgot the actual problem again. Isn't it the usage of the secret token? Which is still there:
https://github.com/davidanthoff/StringBuilders.jl/blob/master/.github/workflows/jlpkgbutler-ci-master-workflow.yml#L39 ?

**Comment by Wikunia** [comment]
Ah I see https://github.com/codecov/codecov-action the secret is not required for public repos.
I switched too: Just needed 3 tries to not mess up the workflow :rofl: 
https://github.com/Wikunia/ConstraintSolver.jl/pull/120

**Comment by Nosferican** [comment]
Perhaps we can put examples on the [repo](https://github.com/julia-actions/julia-processcoverage)?
- [Example](https://github.com/uva-bi-sdad/COVID_Tracking_Clean/blob/master/.github/workflows/ci.yml) of public repo without token

**Comment by DilumAluthge** [comment]
This repo is deprecated.
